id: I5AA21B82
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:30:29+00:00'
last_modified: '2022-06-07T12:24:02.866936+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC349
  title: 'གནས་ཡིག་ལམ་སྟོན་སྒྲོན་མེ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0C0B:
      image_group_id: I4PD4486
      title: ''
      total_pages: 472
      order: 1
      base_file: 0C0B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
