id: P000590
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC349
  title: 'གནས་ཡིག་ལམ་སྟོན་སྒྲོན་མེ། '
  author: ''
  volumes:
    43d89f17070043ff808f9c40fcbe29f4:
      image_group_id: I4PD4486
      title: ''
      volume_number: 1
      total_pages: 472
