id: P000590
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:47.753797
source_metadata:
  id: bdr:W1AC349
  title: 'གནས་ཡིག་ལམ་སྟོན་སྒྲོན་མེ། '
  author: ''
  volumes:
    43d89f17070043ff808f9c40fcbe29f4:
      image_group_id: I4PD4486
      title: ''
      volume_number: 1
      total_pages: 472
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
